:muscle: Updated zshrc to use antigen, also updated basic install

diff --git a/installs/basicInstall b/installs/basicInstall
--- a/installs/basicInstall
+++ b/installs/basicInstall
@@ -1,23 +1,22 @@
 sudo apt-get update
 sudo apt-get install zsh -y 
-
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh::g' | sed 's:chsh -s .*$::g')"
-cd ~/.config
-git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
-git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
-git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
-echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
-
-cd ~/
-
-sudo apt-get install zsh-syntax-highlighting
-
+sudo apt-get install vim
 
 wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
 
-. pullDotfiles
+
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/loket/oh-my-zsh/feature/batch-mode/tools/install.sh)" -s --batch || {
+  echo "Could not install Oh My Zsh" >/dev/stderr
+  exit 1
+}
+
+
+# . pullDotfiles
+
+curl -L git.io/antigen > ~/.oh-my-zsh/plugins/antigen.zsh
 
 git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
 
 ~/.fzf/install
+
 
